### PR TITLE
Feature/lru

### PR DESCRIPTION
**Pull request by shaine**

### CODE REVIEW

**Comment by shaine** [comment]
Creating a PR to help the discussion in #12. Probably needs some cleanup work if it's a good candidate to move forward with.

It's noted that the optimal solution allows a user-provided caching system - I view this PR as an incremental improvement with that being a future, more robust feature change.

**Comment by jchip** [comment]
I prefer to keep `lib/cache-store.js`, maybe change its interface to match that of lru-cache.  ssr-caching could default to lru-cache, or pick one depending on an env.  that way, when debugging and testing, it's still simpler with the simple `lib/cache-store.js`, and switch to lru-cache for more mature implementation.  and finally, ssr-cache could expose an API to allow you to set a custom cache store, as long as it adhere to a few APIs.

**Comment by shaine** [comment]
That sounds reasonable. If I understand correctly, you're thinking `lib/cache-store.js` might still be useful for development of this lib, but end users might prefer to see the lib default to `lru-cache` - thus, having the same interface between both cache implementations allows for a simple adapter? And the definition of such an adapter allows users to supply their own cache implementation should they prefer.

Only point I have in favor of dropping cache-store entirely for lru-cache is that having two caching libs will be a bit confusing, especially when both do the same thing outside of time-based cache invalidation.

Either way, sounds like this PR doesn't help in the direction of those goals, we can close.

**Comment by jchip** [comment]
Hi, just wondering if you are still going to make the changes to support custom cache store?

**Comment by shaine** [comment]
@jchip Not currently planning to update the lib to do that, was only helping discuss possible requirements. Sounds like we've reached a good decision - when we have a little more time (Q1?) we might be able to contribute toward that. Long term, we're evaluating switching to an async cache solution, so helping design a more robust cache engine adapter will be more of a priority at that time.

**Pull request closed without merging**
